Read changelog for full description
Bug fixes:

- Fixed a bug where a duplicated unmute entry is created upon issuing /unmute.

Added features:

- Logging embed for /mute will now display the time elapsed since the user was muted until unmuted.

- Logging embed for /mute will now mention the unmuter.

- Time units in /tempmute will now displayed in singular form if they are equal to 1.

- Time units in /tempmute that are equal to 0 is now omitted.

Enhancements:

- Mute end time for /unmute will now uses int instead of float because the time Regex already does not accept values with decimal point.

- /tempmute notification embed format is now similar to other mod action embeds.

Known bugs:

- Unmuting a bot will result in the following stack trace:

2021-06-28 04:03:31 | discord_slash | ERROR | An exception has occurred while executing command `unmute`:
Traceback (most recent call last):
  File "D:\Programming\venv\lib\site-packages\discord_slash\client.py", line 872, in invoke_command
    await func.invoke(ctx, args)
  File "D:\Programming\venv\lib\site-packages\discord_slash\model.py", line 291, in invoke
    return await coro
  File "D:\Programming\venv\lib\site-packages\discord\ext\commands\core.py", line 374, in __call__
    return await self.callback(*args, **kwargs)
  File "D:\Programming\Chiya\cogs\commands\moderation\mutes.py", line 378, in unmute
    if not await self.send_unmuted_dm_embed(ctx=ctx, member=member, reason=reason):
  File "D:\Programming\Chiya\cogs\commands\moderation\mutes.py", line 98, in send_unmuted_dm_embed
    channel = await member.create_dm()
  File "D:\Programming\venv\lib\site-packages\discord\user.py", line 725, in create_dm
    data = await state.http.start_private_message(self.id)
  File "D:\Programming\venv\lib\site-packages\discord\http.py", line 247, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50007): Cannot send messages to this user